pool:
  vmImage: 'Ubuntu-16.04'

resources:
- repo: self

strategy:
  matrix:
    ginkgo:
      MYSQL_VERSION: 5.6.36
      MONGO_VERSION: 2.6.12
    hawthorn:
      MYSQL_VERSION: 5.6.36
      MONGO_VERSION: 3.2.16

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install pytest
      ls -l
      pwd
      pip install ./egg
      pytest egg
    displayName: 'Run pytest'
  - bash: make build-image
  - bash: make test
  - bash: make test-restore
