trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:
- repo: self

steps:
  - bash: make build-image
  - bash: make test
  - bash: pip install pytest
  - bash: pip install egg
  - bash: make pytest
