
trigger:
- master
pool:
  vmImage: 'Ubuntu-16.04'

resources:
- repo: self


jobs:

- job: CreateImage
  displayName: Create docker image
  steps:
    - bash: make build-image
    - bash: make test
    - bash: make pytest
