pool:
  vmImage: 'Ubuntu-16.04'

resources:
- repo: self

strategy:
  matrix:
    ginkgo:
      MYSQL_VERSION: 5.6.36
      MONGO_VERSION: 2.6.12
    hawthorn:
      MYSQL_VERSION: 5.6.36
      MONGO_VERSION: 3.2.16

steps:
  - script: |
      nohup docker pull alpine:3.10
      nohup docker pull python:3.7-alpine3.10
      nohup docker pull mongo:3.2.16
      nohup docker pull mysql:${MYSQL_VERSION}
      nohup docker pull mongo:${MONGO_VERSION}
      nohup docker pull jeantil/openstack-keystone-swift:pike
    displayName: 'Download docker images in the background'


  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools wheel
      pip install pytest
      ls -l
      pwd
      pip install ./egg
      pytest egg
    displayName: 'Run pytest'
  - bash: make build-image
    displayName: 'Build docker image'
  - bash: make test-dump
    displayName: 'Test dump'
  - bash: make test-restore
    displayName: 'Test restore'
