trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

resources:
- repo: self

strategy:
  matrix:
    ginkgo:
      MYSQL_VERSION: 5.6.36
      MONGO_VERSION: 2.6.12
    hawthorn:
      MYSQL_VERSION: 5.6.36
      MONGO_VERSION: 3.2.16

steps:
  - bash: make build-image
  - bash: make test
  - bash: pip install pytest
  - bash: pip install egg
  - bash: make pytest
